### ISSUE TITLE
support der autoterm heizung

### ISSUE THREAD

**Issue by febu93** [maxlin1/PekawayVANPICORE_homeassistant#3]
Hi, vielen Dank für dieses Projekt!

Eine Frage: Ist auch die Unterstützung der Autoterm Heizung geplant?

**Comment by maxlin1** [comment]
Hallo @febu93 leider derzeit nicht da ich eine Truma 4d habe ist diese geplant. Aber vielleicht findet sich jemand der das mit  integrieren möchte für Pekaway gibt es das ja schon man müsste das nur etwas umschreiben. Ich kann es aber leider nicht testen.

**Comment by k3mpaxl** [comment]
@febu93 Schau mal in meine Repos, ich habe eine Integration für die Autoterm 2d in erstellt:

https://github.com/k3mpaxl/pekaway-ha-autoterm

**Comment by maxlin1** [comment]
Hallo Danke dir, ich hab leider keine Autoterm 2d aber du kannst gerne nen Request zum integrieren stellen.
